export const RENDERER = {
  ATM: "ATM",
  SITE: "Site",
  TAXI: "Taxi",
  TIMETABLE: "Timetable",
  BUSINESS: "business",
  COMMUNITY: "community",
  POSTING: "posting",
  ADVERTISEMENT: "advertisement",
  ATTRACTION: "attraction",
  PROMOTION: "promotion",
  VOUCHER: "voucher",
  EVENT: "event",
  NEWS: "news",
  NOTICE: "notice",
  RESTAURANT: "restaurant",
  TUITION: "tuition",
  PROPERTY: "property",
  DAYTRIP: "daytrip",
  EMERGENCY: "emergency"
};
