/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBulletinItemList: typeof import('./components/global/app-bulletin-item-list.vue')['default']
    AppButton: typeof import('./components/global/app-button.vue')['default']
    AppButtonLocalization: typeof import('./components/global/app-button-localization.vue')['default']
    AppButtonRounded: typeof import('./components/global/app-button-rounded.vue')['default']
    AppCarouselSection: typeof import('./components/global/app-carousel-section.vue')['default']
    AppCategoryItemList: typeof import('./components/global/app-category-item-list.vue')['default']
    AppDialogTitle: typeof import('./components/global/app-dialog-title.vue')['default']
    AppDirectoryItem: typeof import('./components/global/app-directory-item.vue')['default']
    AppDirectorySection: typeof import('./components/global/app-directory-section.vue')['default']
    AppGroupedItemList: typeof import('./components/global/app-grouped-item-list.vue')['default']
    AppMarketingItemList: typeof import('./components/global/app-marketing-item-list.vue')['default']
    AppPageTitle: typeof import('./components/global/app-page-title.vue')['default']
    AppSearchBar: typeof import('./components/global/app-search-bar.vue')['default']
    AppTabPanels: typeof import('./components/global/app-tab-panels.vue')['default']
    AppTabSelect: typeof import('./components/global/app-tab-select.vue')['default']
    AppTextEditor: typeof import('./components/global/app-text-editor.vue')['default']
    GalleryCarouselImage: typeof import('./components/global/gallery-carousel-image.vue')['default']
    LanguageSelect: typeof import('./components/global/language-select.vue')['default']
    ProfileImageSection: typeof import('./components/global/profile-image-section.vue')['default']
    ProfileSettingImage: typeof import('./components/global/profile-setting-image.vue')['default']
    PropertyThumbnailImage: typeof import('./components/global/property-thumbnail-image.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleStatus: typeof import('./components/global/toggle-status.vue')['default']
    VeeInput: typeof import('./components/global/vee-input.vue')['default']
    VeeInputPassword: typeof import('./components/global/vee-input-password.vue')['default']
    VeeInputWhatsapp: typeof import('./components/global/vee-input-whatsapp.vue')['default']
    VeeQTelInput: typeof import('./components/global/vee-q-tel-input.vue')['default']
    VeeSelectWithId: typeof import('./components/global/vee-select-with-id.vue')['default']
    VeeTelInput: typeof import('./components/global/vee-tel-input.vue')['default']
    VeeToggle: typeof import('./components/global/vee-toggle.vue')['default']
  }
}
